version: '3.1'

services:
  mongodb:
    image: bitnami/mongodb
    restart: unless-stopped
    volumes:
      - mongodb:/bitnami

  # tiny-blog-ui:

  tiny-blog-backend:
    image: noahhummel/tiny-blog-backend
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017

volumes:
  mongodb: