version: '3.1'

services:
  mongodb:
    image: bitnami/mongodb
    restart: unless-stopped
    volumes:
      - mongodb:/bitnami

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8088:8080

  # tiny-blog-ui:

  tiny-blog-backend:
    image: noahhummel/tiny-blog-backend
    restart: unless-stopped
    ports:
      - 3000:8080

volumes:
  mongodb: